/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

import "pinia";

/* prettier-ignore */

declare module 'pinia' {
    export interface DefineStoreOptionsBase<S, Store> {
        // allow defining a number of ms for any of the actions
        persist?: any
    }
}
